### ISSUE TITLE
Raw results parser is sensitive to protocol changes

### ISSUE THREAD

**Issue by arielvalentin** [jbussdieker/ruby-rsync#5]
It looks like this gem is only compatible with the default out-format of rsync protocol version 30. Based on some small testing samples I noticed that the protocol seems to change slightly with every version.  

(Mac OSX Mavericks) rsync  version 2.6.9  protocol version 29

> The  "%i" escape has a cryptic output that is 9 letters long.  The general format is like the string YXcstpogz, where Y is replaced by the type of update being done, X is replaced by the file-type, and the other letters represent attributes that may be output if they are being modified.

(CentOS 6.5) rsync  version 3.0.9  protocol version 30

> The “%i” escape has a cryptic output that is 11 letters long.  The general format is like the string YXcstpoguax, where Y is replaced by the  type of update being done, X is replaced by the file-type, and the other letters represent attributes that may be output if they are being modified.

(Mac OSX Mavericks - brew) rsync  version 3.1.1  protocol version 31

> The "%i" escape has a cryptic output that is 11 letters long.  The general format is like the string YXcstpoguax, where Y is replaced by the type of update being done, X is replaced by the file-type, and the other letters represent attributes that may be output if they are being modified.

And despite what the man page says, it's 12 characters. ">f++++++++++ bar.txt"

This makes the library extremely sensitive to changes to the rsync version. It would be nice if one could either specify or the library to substitute its parser algorithm based on the installed version of rsync.

**Comment by jbussdieker** [comment]
Nice catch. I just started some testing around this. https://travis-ci.org/jbussdieker/ruby-rsync/builds/56263242
